### ISSUE TITLE
Creating kernel models with get_kernel doesn't work

### ISSUE THREAD

**Issue by PaulPOOFA** [allogamous/EnvRtype#12]
Thanks for creating the package. 

I am facing difficulty creating kernel models EMM, EMDs, RMMM and RNMDs based on the toy data set in the package. I am receiving error message: length of 'dimnames' [1] not equal to array extent. I do not know how to fix this.

EMM   = get_kernel(K_G = KG, K_E = KE, y = y,gid = gid,env = env,  data = maizeYield, model = "EMM") 
EMDs  = get_kernel(K_G = KG, K_E = KE, y = y,gid = gid,env = env,  data = maizeYield, model = "EMDs") 
RMMM  = get_kernel(K_G = KG, K_E = KE, y = y,gid = gid,env = env,  data = maizeYield, model = "RNMM") 
RNMDs = get_kernel(K_G = KG, K_E = KE, y = y,gid = gid,env = env,  data = maizeYield, model = "RNMDs") 

Error in dimnames(x) <- dn : 
  length of 'dimnames' [1] not equal to array extent

Thanks.

**Comment by huw143** [comment]
Any solution for this, I met the same issue here. 

Thanks for your helps,

Tiger

**Comment by PaulPOOFA** [comment]
Hello,

The question has been closed. Can you send it the problem here?

Thanks.

**Comment by huw143** [comment]
Thank you Paul for your quick response, 

The question is same: 


EMM = get_kernel(K_G = KG, K_E = KE, y = y,gid = gid,env = env, data = maizeYield, model = "EMM")
EMDs = get_kernel(K_G = KG, K_E = KE, y = y,gid = gid,env = env, data = maizeYield, model = "EMDs")
RMMM = get_kernel(K_G = KG, K_E = KE, y = y,gid = gid,env = env, data = maizeYield, model = "RNMM")
RNMDs = get_kernel(K_G = KG, K_E = KE, y = y,gid = gid,env = env, data = maizeYield, model = "RNMDs")

Error in dimnames(x) <- dn :
length of 'dimnames' [1] not equal to array extent


But I figured it out already, 

This is because the gid in the dataframe of maizeYield are not the same format, some of them are character, while some of them are not. I used the following R script to fix it.

maizeYield$gid <- as.character(maizeYield$gid)


Thanks for your contribution to this R package, which is amazing!

Best regards,

Tiger

**Comment by PaulPOOFA** [comment]
I am glad you figured it out. Thanks.
